_: {
  # zsh as the default login shell for the primary user.
  flake.nixosModules.zsh = { pkgs, config, ... }: {
    programs.zsh.enable = true;
    users.users.${config.hostConfig.user.name}.shell = pkgs.zsh;
  };

  # User-level zsh config, kept split across ~/.zsh (general config/functions)
  # and ~/.alias (aliases), both sourced from the home-manager-managed
  # .zshrc. Also wires up asdf-vm's shell integration (no NixOS/home-manager
  # module exists for it, so its shipped profile.d script is sourced
  # directly) and powerlevel10k (theme + the p10k.zsh config generated by
  # `p10k configure`, kept alongside this module).
  flake.homeModules.zsh = { pkgs, lib, ... }: {
    home.packages = [ pkgs.asdf-vm ];

    programs.zoxide = {
      enable = true;
      enableZshIntegration = true;
    };

    home.file.".alias".text = ''
      # Shell aliases.

      alias ls='ls --color'
      alias ll='ls -ltra --color'
      alias vim='nvim'
      alias vi='nvim'
      alias p='cd ~/Projects'
    '';

    home.file.".p10k.zsh".source = ./p10k.zsh;

    programs.zsh = {
      enable = true;
      enableCompletion = true;
      initContent = lib.mkMerge [
        # Load the theme as early as possible, before anything else prints --
        # required for powerlevel10k's instant-prompt feature to work.
        (lib.mkBefore ''
          source "${pkgs.zsh-powerlevel10k}/share/zsh-powerlevel10k/powerlevel10k.zsh-theme"
        '')
        ''
          source "${pkgs.asdf-vm}/etc/profile.d/asdf-prepare.sh"
          [ -f "$HOME/.alias" ] && source "$HOME/.alias"
        ''
        # p10k's own convention is to source ~/.p10k.zsh last, after the theme
        # and the rest of .zshrc have loaded.
        (lib.mkAfter ''
          [ -f "$HOME/.p10k.zsh" ] && source "$HOME/.p10k.zsh"
        '')
      ];
    };
  };
}
