_: {
  # zsh as the default login shell for the primary user.
  flake.nixosModules.zsh = { pkgs, config, ... }: {
    programs.zsh.enable = true;
    users.users.${config.hostConfig.user.name}.shell = pkgs.zsh;
  };

  # User-level zsh config, kept split across ~/.zsh (general config/functions)
  # and ~/.alias (aliases), both sourced from the home-manager-managed
  # .zshrc. Also wires up asdf-vm's shell integration (no NixOS/home-manager
  # module exists for it, so its shipped profile.d script is sourced
  # directly) and powerlevel10k (theme + the p10k.zsh config generated by
  # `p10k configure`, kept alongside this module).
  flake.homeModules.zsh = { pkgs, lib, asdfPlugins, ... }: {
    home.packages = [ pkgs.asdf-vm ];

    # Install each configured asdf plugin (programs.asdf.plugins, set by
    # profiles -- see profiles/desktop.nix for the shared base list and
    # profiles/work.nix for the work-only additions) on activation. `|| true`
    # because `asdf plugin add` errors if a plugin is already installed.
    home.activation.asdfPlugins = lib.hm.dag.entryAfter [ "writeBoundary" ] (
      let
        asdf = lib.getExe pkgs.asdf-vm;
      in ''
        # The activation script's PATH is a minimal, curated one (no git) --
        # `asdf plugin add` shells out to git to clone the plugin repo, so it
        # needs to be added explicitly.
        export PATH="${pkgs.git}/bin:$PATH"
      ''
      + lib.concatMapStringsSep "\n" (name: ''
        run ${asdf} plugin add ${lib.escapeShellArg name} || true
      '') asdfPlugins
    );

    programs.zoxide = {
      enable = true;
      enableZshIntegration = true;
    };

    home.file.".alias".text = ''
      # Shell aliases.

      alias ls='ls --color'
      alias ll='ls -ltra --color'
      alias vim='nvim'
      alias vi='nvim'
      alias p='cd ~/Projects'
    '';

    home.file.".p10k.zsh".source = ./p10k.zsh;

    programs.zsh = {
      enable = true;
      enableCompletion = true;
      initContent = lib.mkMerge [
        # Load the theme as early as possible, before anything else prints --
        # required for powerlevel10k's instant-prompt feature to work.
        (lib.mkBefore ''
          source "${pkgs.zsh-powerlevel10k}/share/zsh-powerlevel10k/powerlevel10k.zsh-theme"
        '')
        ''
          # zsh auto-selects vi keybindings whenever $EDITOR/$VISUAL contains
          # the substring "vi" -- which "nvim" does (programs.neovim.defaultEditor
          # sets EDITOR=nvim in hosts/common.nix). Force emacs bindings so
          # Ctrl+A/Ctrl+E etc. keep working regardless of $EDITOR.
          bindkey -e

          # Alacritty sends xterm-style CSI sequences for Alt+Left/Right
          # (`\e[1;3D`/`\e[1;3C`), which aren't in zsh's default emacs
          # keymap (NixOS's /etc/zinputrc only covers plain arrows/Home/End/
          # etc., not modified ones) -- bind them to word-jump explicitly.
          bindkey '^[[1;3D' backward-word
          bindkey '^[[1;3C' forward-word

          source "${pkgs.asdf-vm}/etc/profile.d/asdf-prepare.sh"
          [ -f "$HOME/.alias" ] && source "$HOME/.alias"
        ''
        # p10k's own convention is to source ~/.p10k.zsh last, after the theme
        # and the rest of .zshrc have loaded.
        (lib.mkAfter ''
          [ -f "$HOME/.p10k.zsh" ] && source "$HOME/.p10k.zsh"
        '')
      ];
    };
  };
}
